version: 2
jobs:
 build:
  environment:
   cumulusci.core.keychain.EnvironmentProjectKeychain
  machine: 
   python:
    version: 3.7.0
  steps:
  - run :  'pip install --upgrade pip'
  - run :   'pip install --upgrade cumulusci'
  - run :   'git clone https://github.com/prashant-22/NewRespository'
workflows:
  version: 2
  build:
    jobs:
      - build