defaults: &defaults
  docker:
    - image: circleci/python:3.6-browsers
  environment:
    - BROWSER: headlesschrome
  working_directory: ~/repo

version: 2
jobs:
    test_release:
    <<: *defaults
        environment:
        CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
    steps:
      - checkout
      - run:
          name: Skip unless master or PR build
          command: |
            if [ "$CIRCLE_BRANCH" != "master" ] && [ -z "$CIRCLE_PULL_REQUEST" ]; then
              circleci step halt
            fi
    - run:
          name: Create Package
          command: |
           cci task run update_package_xml