machine:
  python:
    version: 3.7.0
environment:
  CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
dependencies:
  override:
    - 'pip install --upgrade pip'
    - 'pip install --upgrade -r requirements.txt'
test:
  override:
    - 'cci flow run ci_feature_cumulus --org feature'
  post:
    - 'mkdir -p $CIRCLE_TEST_REPORTS/junit/'
    - 'cp test_results.xml $CIRCLE_TEST_REPORTS/junit/'