defaults: &defaults
  docker:
    - image: circleci/python:3.6-browsers
  environment:
    - BROWSER: headlesschrome
  working_directory: ~/repo


version: 2
jobs:

test_release:
    <<: *defaults
    environment:
      CUMULUSCI_KEYCHAIN_CLASS: cumulusci.core.keychain.EnvironmentProjectKeychain
    steps:
    - checkout
    - run:  
         name: skip unless master or pre build
         command: |
           if [ "$CIRCLE_BRANCH" != "master" ] && [ -z "$CIRCLE_PULL_REQUEST" ]; then
              circleci step halt
            fi
    -run:
     name: create a package
     command: |
      cci task run update_package_xml

workflow:
  version: 2
  test:
  jobs:
   - test_release