version: 2
jobs:
 build:
  environment:
   cumulusci.core.keychain.EnvironmentProjectKeychain
  steps:
  - run :  'pip install --upgrade pip'
  - run :   'pip install --upgrade cumulusci'

workflows:
  version: 2
  build:
    jobs:
      - build